language: php

# use the new container infrastructure
sudo: false

php:
  - "5.5"
  - "5.6"
  - '7.0'
  - "hhvm"

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then
        phpenv config-rm xdebug.ini;
      fi
    - composer self-update --no-interaction

install:
    - composer install --prefer-dist --no-interaction

script:
    - ./bin/phpspec run
    - ./bin/php-cs-fixer fix --dry-run -v --diff --config-file=.php_cs.php
